[project]
name = "lecproc"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "anyio[trio]>=4.10.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "rich>=14.1.0",
    # audio2text
    "faster-whisper>=1.2.0",
    "litellm>=1.75.5.post1",
    "natsort>=8.4.0",
]

[dependency-groups]
lint = [
    "basedpyright>=1.31.1",
    "mypy>=1.17.1",
    "ruff>=0.12.8",
]



[tool.basedpyright]
typeCheckingMode = "recommended"
reportMissingTypeStubs = false
reportImplicitRelativeImport = false
