name: Style and Type Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install project dependencies
        run: uv sync --all-groups --all-extras --frozen

      - name: Run style and type checks
        run: just check
